spring:
  security:
    logout:
      logout-url: /logout
      logout-success-url: /login?logout
      permit-all: true
    authorize-requests:
      - ant-matchers: /login**, /logout**
        permit-all: true
      - any-request: true
        authenticated: true





  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_security
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


  mail:
    host: smtp.gmail.com
    port: 587
    username: rahmafarhat9@gmail.com
    password: dcyaydfvntixmjia
  properties:
    mail:
      transport:
        protocol: smtp
      smtp:
        auth: true
        starttls:
          enable: true
      debug: true
server:
  port: 8087
application:
  security:
    jwt:
      secret-key: 586B633834416E396D7436753879382F423F4428482B4C6250655367566B5970
      expiration: 900000 #  15 min in ms
      cookie-name: jwt-cookie
      refresh-token:
        expiration: 1296000000 # 15 days in ms
        cookie-name: refresh-jwt-cookie
file:
  upload-dir: /api/files/upload
services:
  forgot-password: http://localhost:4200/forgot-password